#!/usr/bin/env bash

export HYPRCORE_SHARE_PATH="$HOME/.local/share/hyprcore"
export HYPRCORE_STATE_PATH="$HOME/.local/state/hyprcore"

export HYPRCORE_SCRIPTS="$HYPRCORE_SHARE_PATH/scripts"
export HYPRCORE_SCRIPTS_BIN="$HYPRCORE_SCRIPTS/bin"
export HYPRCORE_SCRIPTS_CONFIG="$HYPRCORE_SCRIPTS/config"
export HYPRCORE_SCRIPTS_INSTALL="$HYPRCORE_SCRIPTS/install"
export HYPRCORE_SCRIPTS_PREREQ="$HYPRCORE_SCRIPTS/prerequisites"


export HYPRCORE_CONFIG="$HYPRCORE_SHARE_PATH/config"
export HYPRCORE_DEFAULT="$HYPRCORE_SHARE_PATH/default"
export HYPRCORE_LOG="$HYPRCORE_STATE_PATH/install.log"
export HYPRCORE_CACHE="$HYPRCORE_STATE_PATH/cache"

export PATH="$HYPRCORE_SCRIPTS_BIN:$PATH"
