#!/usr/bin/env bash

HYPRCORE_SHARE_PATH="$HOME/.local/share/hyprcore"
mkdir -p $HYPRCORE_SHARE_PATH

HYPRCORE_STATE_PATH="$HOME/.local/state/hyprcore"
mkdir -p $HYPRCORE_STATE_PATH

HYPRCORE_BIN="$HYPRCORE_SHARE_PATH/bin"
HYPRCORE_SCRIPTS="$HYPRCORE_SHARE_PATH/scripts"
cp -R scripts $HYPRCORE_SCRIPTS

HYPRCORE_SCRIPTS_CONFIG="$HYPRCORE_SCRIPTS/config"
HYPRCORE_SCRIPTS_INSTALL="$HYPRCORE_SCRIPTS/install"
HYPRCORE_SCRIPTS_PREREQ="$HYPRCORE_SCRIPTS/prerequisites"


HYPRCORE_CONFIG="$HYPRCORE_SHARE_PATH/config"
cp -R config $HYPRCORE_CONFIG

HYPRCORE_DEFAULT="$HYPRCORE_SHARE_PATH/default"
cp -R default $HYPRCORE_DEFAULT

HYPRCORE_LOG="$HYPRCORE_STATE_PATH/install.log"

export PATH="$HYPRCORE_BIN:$PATH"
